feature_engineering:
  n_components: 3

model_training:
  n_estimators: 40
  max_depth: 15
  bootstrap: False
  criterion: gini

model_evaluation:
  n_components: 3
  n_estimators: 40
  max_depth: 15
  bootstrap: False
  criterion: gini